# Generated by Django 5.0.7 on 2024-07-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Баланс на момент поступления'),
            preserve_default=False,
        ),
    ]
